<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="IETSMH02D098" name="Com.GeneoStudent.Testcases.CoverPageTest" tests="1" failures="1" timestamp="16 Mar 2018 12:20:13 GMT" time="22.385" errors="0">
  <testcase name="Cover_Page_menu_Change_Password_Button_Test" time="22.385" classname="Com.GeneoStudent.Testcases.CoverPageTest">
    <failure type="java.lang.AssertionError" message="Change Password window Failed to open expected [false] but found [true]">
      <![CDATA[java.lang.AssertionError: Change Password window Failed to open expected [false] but found [true]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertFalse(Assert.java:62)
	at Com.GeneoStudent.Testcases.CoverPageTest.Cover_Page_menu_Change_Password_Button_Test(CoverPageTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- Cover_Page_menu_Change_Password_Button_Test -->
</testsuite> <!-- Com.GeneoStudent.Testcases.CoverPageTest -->
